# Generated by Django 4.0.3 on 2022-03-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientbulkupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_country',
            field=models.CharField(max_length=100),
        ),
    ]
