# Generated by Django 4.0.4 on 2022-05-03 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_category_name_category_alter_city_name_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=6)),
                ('lng', models.CharField(max_length=6)),
                ('lastUpdate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='country_modifed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('idRequest', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('RequestDate', models.DateField(default=datetime.date.today)),
                ('latPickUp', models.CharField(max_length=6)),
                ('lngpickup', models.CharField(max_length=6)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.driver')),
            ],
        ),
    ]
